### PR TITLE
Bug 2087042: Rebase cloud-provider-azure 22.06.2022

### PR DESCRIPTION
**Pull request by lobziik**
This commit rebases the cloud-provider-azure openshift patches on top of the kubernetes-sigs/cloud-provider-azure master branch after 1.24.2 release.
There are several commits that we carry on top of the upstream azure-cloud-provider and the rebase process allows us to preserve those. Here is a description of the process I used to create this PR.

(replicated @elmiko's process within openshift/kubernetes-autoscaler)

Process

First we need to identify the carry commits that we currently have, this is done against our previous rebase (or fork in this case) to catch new changes. Once identified we will drop commits which have merged upstream and only carry unique commits. (see below for the carried and dropped commits).

Identify carry commits:

```git log --oneline --no-merges 303f6ddce98eb78d9858ae17abee46f67a08135f..openshift/master```

where `303f6d` is the last upstream commit in our fork. This is the
list of commits we will need to apply onto the new upstream version of the
cloud-provider-azure. ideally, some of these commits can be dropped.

After identifying the carry commits, the next step is to create the new commit-tree that will be used for the rebase and then cherry pick the carry commits into the new branch. The following commands cover these steps:
```
$ git remote update # make sure we update our refs
$ git checkout 2888dc7a4be361cc6e45d92ab5ce8478b7fa3b2a # master HEAD after 1.24.2 release
$ git checkout -b merge-tmp # create a temporary branch for our merge commit
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge kubernetes-sigs/azure-cloud-provider 22-07-2021' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - # create a new merge commit for our history
9cbc9d4aaf6069b641ed9a10dbfc135affedec9d # id of new merge commit
$ git branch merge-22-06-2022 9cbc9d4aaf6069b641ed9a10dbfc135affedec9d # create a new branch for the cherry-pick work
$ git checkout merge-22-06-2022
$ git cherry-pick <carry commits> # cherry pick the needed commits into the new branch
```

With the merge-22-06-2022 branch in place, I cherry picked the carry commits which we should carry.

Carried Commits

These commits are integral to our CI platform, or are specific to the releases we create for OpenShift.

```
e56be7 UPSTREAM: <carry>: set GOARCH appropriately
53c43db UPSTREAM: <carry>: update to golang 1.17, sync cloud-node-manager and cloud-controller-manager with latest OCP release
e72384 UPSTREAM: <carry>: add dockerfiles for openshift builds, openshift specific makefile extension, openshift specific hack scripts
70dc69 UPSTREAM: <carry>: delete .github directory
e99493 UPSTREAM: <carry>: Update OWNERS file
```

Note: github dir removal commit was reordered with 

Changed Commits

1. All commits related to OWNERS file was squashed into `e99493 UPSTREAM: <carry>: Update OWNERS file`

2. ```8a35d2 UPSTREAM: <carry>: Fix "verify" job cloud-team-rebase-bot``` was squashed into ```e72384 UPSTREAM: <carry>: add dockerfiles for openshift builds, openshift specific makefile extension, openshift specific hack scripts```

3. ```70dc69 UPSTREAM: <carry>: delete .github directory``` was extended with deletion of newly appeared files

4. ART commits and golang update was squashed into one commit ```53c43db```

Dropped Commits
```
f804be UPSTREAM: <carry>: update to golang 1.17
a0285d UPSTREAM: <carry>: Updating ose-azure-cloud-node-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/3dea8426481b269476342fc0a631273f32ce691e/images/ose-azure-cloud-node-manager.yml
5b3462 UPSTREAM: <carry>: Updating ose-azure-cloud-controller-manager images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/3dea8426481b269476342fc0a631273f32ce691e/images/ose-azure-cloud-controller-manager.yml
8a35d2 UPSTREAM: <carry>: Fix "verify" job
bf9a4c UPSTREAM: <carry>: Update owners file 
3fa1ff UPSTREAM: <carry>: Add component info to the OWNERS 
dd6437 UPSTREAM: <carry>: Remove upsteam approvers and reviewers 
6e279c UPSTREAM: <carry>: Add approvers 
4c6c3d UPSTREAM: <carry>: Add component info to the OWNERS file 
129f0a Remove upsteam approvers and reviewers 
dd13fa Add approvers 
```

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
rebase generally looks good to me
/lgtm

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
