### PR TITLE
Bug 2087042: Merge https://github.com/kubernetes-sigs/cloud-provider-azure:master into master 

### PR DESCRIPTION
**Pull request by Fedosin**

### CODE REVIEW

**Comment by elmiko** [comment]
@Fedosin is the broken git-history test a known issue for this repo when doing the rebase?

**Comment by elmiko** [comment]
i notice we have a merge commit as the latest here, but in the aws rebase we don't. see https://github.com/openshift/cloud-provider-aws/pull/22/commits

**Comment by Fedosin** [comment]
Yeah, verify-git-history is expected to fail on such rebases... Merge commit was added to fix github's conflicts when merging the rebase PR.

**Comment by elmiko** [comment]
thanks Mike!
/approve
/lgtm

**Pull request merged**
