### PR TITLE
OCPBUGS-28244: Account for endpoint not being rerturned when building cloud configuration

### PR DESCRIPTION
**Pull request by theobarberbany**
This change updates AzureCloudConfigFromURL to check that the URL
(ResourceManagerEndpoint) that is used to build the config has been
returned. If it has not, it sets it using the URL provided.

This avoids the case where the endpoint is used to build config, but
does not return it's self - causing the created configuration to fail.

To make this work, we must update go.mod to replace the vendored package
with the one in the fork, and revendor. If we do not revendor, the
changes in the fork are not propagated to the /vendor directory and are
silently ignored.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
this looks good to me, is there any unit testing we could add to confirm the behavior?

e.g. could we add something to existing tests, i don't think we need to make a new test suite for this.

**Comment by theobarberbany** [comment]
@elmiko I've added a test in a separate commit. 

In order to do this i've had to update the azclient module go.mod and , which leaves us with a pretty huge diff  (any change requires a revendor) :(

I'm not sure if there's another approach here that is nicer  /  more flexible. It feels insane for this to be a 1000+ file change :/

**Comment by elmiko** [comment]
> I'm not sure if there's another approach here that is nicer / more flexible. It feels insane for this to be a 1000+ file change for what is actually changing a single file and it's test... :/ Perhaps if i drop the klog addition, we won't have such a large diff?

agreed, it doesn't feel good to force this large of a dependency update. i'd say try it out without the klog change just to see if it does reduce the amount of change.

the test itself looks good to me, but do we need a negative assertion as well?

**Comment by theobarberbany** [comment]
Closing this, as we've taken the issue upstream :

https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5643

https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5651

**Pull request closed without merging**
